export { default as TransformIcon }    from '@mui/icons-material/Transform';
export { default as CompressIcon }      from '@mui/icons-material/Compress';
export { default as AutoLayoutIcon }    from '@mui/icons-material/GridView';
export { default as LockIcon }          from '@mui/icons-material/Lock';
export { default as PublicIcon }        from '@mui/icons-material/Public';
export { default as SaveIcon }          from '@mui/icons-material/Save';
export { default as VisibilityIcon }    from '@mui/icons-material/Visibility';
export { default as VisibilityOffIcon } from '@mui/icons-material/VisibilityOff';
export { default as SparkleIcon }       from '@mui/icons-material/AutoAwesome';
